HOTFIX: Safely run apt-get
VRVDR-49495

diff --git a/scripts/vyatta-squashfs-chroot b/scripts/vyatta-squashfs-chroot
--- a/scripts/vyatta-squashfs-chroot
+++ b/scripts/vyatta-squashfs-chroot
@@ -43,6 +43,8 @@ if [[ -z $COMMAND ]]; then
 	fail_exit "No command provided"
 fi
 
+lecho "Starting Vyatta Overlay mounter"
+
 ROOTFS_DEV=$(what_is_mounted_on /boot)
 if [[ -z $ROOTFS_DEV ]]; then
 	logger error "$0: Failed to get root device for $TARGET_IMAGE"
@@ -81,6 +83,7 @@ if ! try_mount $margs; then
 	logger error "$0: Cannot mount overlay"
 	fail_exit "Cannot mount overlay"
 fi
+lecho "Successfully set up overlay dir."
 
 if [[ $COMMAND == "LIST" ]]; then
 	run_command dpkg --list --root=${merged}
@@ -122,21 +125,27 @@ elif [[ $COMMAND == "INSTALL" ]]; then
 		fail_exit "Failed to scan packages"
 	fi
 	popd &>/dev/null
-	run_command cat > ${merged}/etc/apt/sources.list.d/hotfix.list << EOF
+	cat > ${merged}/etc/apt/sources.list.d/hotfix.list << EOF
 deb file:${TEMP_APT_REPO_DIR} ./
 EOF
 	# Run apt-get upgrade
 	APT_ARGS="--allow-downgrades --allow-remove-essential --allow-change-held-packages"
-	run_command chroot ${merged} logrotate -f /etc/logrotate.d/apt
-	export DEBIAN_FRONTEND=noninteractive 
-	run_command chroot ${merged} apt-get update
-	run_command chroot ${merged} apt-get $APT_ARGS --yes --dry-run dist-upgrade
+	run_command chroot ${merged} /bin/bash -c \
+		"DEBIAN_FRONTEND=noninteractive apt-get update"
+	if [[ $? != 0 ]]; then
+		safe_umount
+		logger error "$0: Apt-get update failed"
+		fail_exit "Apt-get update failed"
+	fi
+	run_command chroot ${merged} /bin/bash -c \
+		"DEBIAN_FRONTEND=noninteractive apt-get $APT_ARGS --yes --dry-run dist-upgrade"
 	if [[ $? != 0 ]]; then
 		safe_umount
 		logger error "$0: Apt-get dry run failed"
 		fail_exit "Apt-get dry run failed"
 	fi
-	run_command chroot ${merged} apt-get $APT_ARGS --yes dist-upgrade
+	run_command chroot ${merged} /bin/bash -c \
+		"DEBIAN_FRONTEND=noninteractive apt-get $APT_ARGS --yes dist-upgrade"
 	if [[ $? != 0 ]]; then
 		safe_umount
 		logger error "$0: Apt-get upgrade failed"
@@ -144,7 +153,8 @@ EOF
 	fi
 	run_command rm -rf ${merged}/${TEMP_APT_REPO_DIR}
 	run_command rm -rf ${merged}/etc/apt/sources.list.d/hotfix.list
-	run_command chroot ${merged} apt-get clean
+	run_command chroot ${merged} /bin/bash -c \
+		"DEBIAN_FRONTEND=noninteractive apt-get clean"
 else
 	safe_umount
 	fail_exit "Command [$COMMAND] not supported"
